# Generated by Django 4.2.5 on 2023-11-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_profile_referral_code_profile_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='personal_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
