# Generated by Django 4.2.5 on 2023-10-09 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_category_question_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
