# Generated by Django 4.2.5 on 2023-11-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0008_board_question_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='initial_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
    ]
